spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:6600/CarCareCenter?createDatabaseIfNotExist=true
    username: root
    password: admin
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always
---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://db:3306/CarCareCenter?createDatabaseIfNotExist=true
    username: root
    password: admin
  config:
    activate:
      on-profile: prod